export default {
	province: 'province',
	regency: 'regency',
	district: 'district',
	user: 'user',
	admin: 'admin',
	product: 'product',
	product_variation: 'product_variation',
	product_image: 'product_image',
	product_facility: 'product_facility',
	facility: 'facility',
	product_custom_facility: 'product_custom_facility',
	facility_image: 'facility_image',
	product_order: 'product_order',
	review: 'review',
	review_image: 'review_image',
};
